### ISSUE TITLE
Alternative Database?

### ISSUE THREAD

**Issue by cloudlakecho** [IBM/example-health-machine-learning#5]
The dataset is from electronic health records in a database on a z/OS server. The z/OS server looks like required many steps of installation at the server. Is there alternative database, who have a personal computer?

**Comment by ghost** [comment]
Hi @cloudlakecho  ... this code pattern is designed to highlight IBM Z, so there is no alternative DB.

If you'd like to get your hands on some demos of z/OS, head over to the IBM Z Software Trials (Z Trials) here: https://www.ibm.com/it-infrastructure/z/software-trials.  These provide a quick, free way for people to explore different scenarios with different products related to z/OS.

**Comment by cloudlakecho** [comment]
@mattcousens Thanks for the information and suggestion. I visited the link and it has couple of options. Which one do you suggest someone, who like learning about IBM Z Data Base, which is used in this repository?

**Comment by ghost** [comment]
Hmm, I don't think any of the Z Trials will really highlight a database.  The z/OS Connect trial shows how to expose some assets residing on z/OS as REST API's but it doesn't cover the back-end database.

If you're interested in foundation z/OS, you could try https://masterthemainframe.com.  The competition is open for students registering from .edu email accounts but check it out for details even if you're not a student.
